# Generated by Django 5.2.15 on 2026-06-23 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('application_received', 'Application received'), ('application_accepted', 'Application accepted'), ('application_rejected', 'Application rejected'), ('agreement_to_validate', 'Agreement to validate'), ('internship_activated', 'Internship activated'), ('task_assigned', 'Task assigned'), ('task_submitted', 'Task submitted'), ('task_validated', 'Task validated'), ('task_changes_requested', 'Task changes requested'), ('report_submitted', 'Report submitted'), ('report_validated', 'Report validated'), ('report_changes_requested', 'Report changes requested'), ('new_message', 'New message'), ('evaluation_submitted', 'Evaluation submitted')], max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx')],
            },
        ),
    ]
