# Generated by Django 5.2.15 on 2026-06-22 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0002_report_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluator_type', models.CharField(choices=[('company', 'Company'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=10)),
                ('scores', models.JSONField(default=dict)),
                ('comment', models.TextField(blank=True)),
                ('total_score', models.FloatField(default=0)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='internships.internship')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['internship', 'evaluator_type'], name='evaluations_interns_4c56a4_idx')],
                'constraints': [models.UniqueConstraint(fields=('internship', 'evaluator_type'), name='unique_evaluation_per_type')],
            },
        ),
    ]
